# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18e242b277b3f7fe8eb7d9c151b238d88eca55cff502a65274d72b3a2593872f47e68e49d2617c5543ecf4521f5c09c40158b8de340ed9198272a69529292a2a

test:
  secret_key_base: 5dc4216ad457465e7b7cf44539c21cca95255dc8b7ea4c5b901346e88fb4158f2bab55757d0a0fb4e109c8531b41b3cd3fd62484d213e5ead77542aed0d0447b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: c4a3f7e5088f2eb629637300a1415717adb6d392c33de99e09840f0eca4db35ed30a3b40bc2cdacbd1645f8d1d95c8e4e8d0185e4cea256e92dd6aae16eb8e26
